GET http://localhost:3000/user


###
GET http://localhost:3000/admin

###
POST http://localhost:3000/user/logIn
Content-Type: application/json

{
    "email": "sara@gmail.com",
    "passWord": "sara",
    "subscribe": ""
}

###
PUT http://localhost:3000/user/update
Content-Type: application/json

{
    "_id":"628ce16df795956d809b0c9c",
    "subscribe": "true"
}

###
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "email": "sarita@gmail.com",
    "passWord": "sarita",
    "subscribe": ""
}

###

# POST http://localhost:3000/user/newsLetter
# Content-Type: application/json

# {
#     "_id": "628ce191f795956d809b0ca2"
# }